CREATE TABLE `person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MANOJ','SUTHAR','JODHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MwerNOJ','SUTHAR','JODHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MwerNOJ','SUTHAR','JODerHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MwerNOJ','SUTHAR','JODerHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MwerNOJ','SUTHAR','JODerHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MwerNOJ','SUTHAR','JODerHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('M5NOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MANOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MANOJ','SUTHAR','JODwereHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MANOJ','SU5AR','JODHwerePUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODHwerePUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODHwerePUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODHwerePUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODerPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODerPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODerPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MA345NOJ','SU5AR','JODHPUR');
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,CITY) VALUES('MANOJ','SU5AR','JODHPUR');